from django import forms

class ChecklistForm(forms.Form):
    
    monitoring_start = forms.DateTimeField(widget= forms.DateTimeField)
    
    q1 = forms.CharField(widget=forms.CharField)
    q2 = forms.CharField(widget=forms.CharField)
    q3 = forms.CharField(widget=forms.CharField)
    q4 = forms.CharField(widget=forms.CharField)
    q5 = forms.CharField(widget=forms.CharField)
    q6 = forms.CharField(widget=forms.CharField)
    q7 = forms.CharField(widget=forms.CharField)
    q8 = forms.CharField(widget=forms.CharField)
    q9 = forms.CharField(widget=forms.CharField)
    q10 = forms.CharField(widget=forms.CharField)
    q11 = forms.CharField(widget=forms.CharField)
    q12 = forms.CharField(widget=forms.CharField)
    q13 = forms.CharField(widget=forms.CharField)
    q14 = forms.CharField(widget=forms.CharField)
    q15 = forms.CharField(widget=forms.CharField)
    q16 = forms.CharField(widget=forms.CharField)
    q17 = forms.CharField(widget=forms.CharField)
    q18 = forms.CharField(widget=forms.CharField)
    q19 = forms.CharField(widget=forms.CharField)
    q20 = forms.CharField(widget=forms.CharField)
    q21 = forms.CharField(widget=forms.CharField)
    q22 = forms.CharField(widget=forms.CharField)
    q23 = forms.CharField(widget=forms.CharField)
    q24 = forms.CharField(widget=forms.CharField)
    q25 = forms.CharField(widget=forms.CharField)
    q26 = forms.CharField(widget=forms.CharField)
    q27 = forms.CharField(widget=forms.CharField)
    q28 = forms.CharField(widget=forms.CharField)
    q29 = forms.CharField(widget=forms.CharField)
    q30 = forms.CharField(widget=forms.CharField)
    q31 = forms.CharField(widget=forms.CharField)
    q32 = forms.CharField(widget=forms.CharField)
    q33 = forms.CharField(widget=forms.CharField)
    q34 = forms.CharField(widget=forms.CharField)
    q35 = forms.CharField(widget=forms.CharField)
    q36 = forms.CharField(widget=forms.CharField)
    q37 = forms.CharField(widget=forms.CharField)
    q38 = forms.CharField(widget=forms.CharField)
    q39 = forms.CharField(widget=forms.CharField)
    q40 = forms.CharField(widget=forms.CharField)
    q41 = forms.CharField(widget=forms.CharField)
    q42 = forms.CharField(widget=forms.CharField)
    q43 = forms.CharField(widget=forms.CharField)
    q44 = forms.CharField(widget=forms.CharField)
    q45 = forms.CharField(widget=forms.CharField)
    q46 = forms.CharField(widget=forms.CharField)
    q47 = forms.CharField(widget=forms.CharField)
    q48 = forms.CharField(widget=forms.CharField)
    q49 = forms.CharField(widget=forms.CharField)
    
    