# Generated by Django 3.2.16 on 2022-12-26 17:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(help_text='Unique ID for this particular users across user', primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email address')),
                ('nickname', models.CharField(max_length=30, unique=True, verbose_name='Nickname')),
                ('first_name', models.CharField(max_length=10, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=10, verbose_name='Last Name')),
                ('address', models.CharField(default=True, max_length=100, unique=True, verbose_name='Address')),
                ('phone_number', models.CharField(default=True, max_length=30, verbose_name='Phone Number')),
                ('division', models.CharField(choices=[('매니저', 'Manager'), ('업소', 'Lodge')], default=True, help_text='매니저/업소 중 분류를 입력하세요', max_length=10)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date joined')),
                ('salt', models.CharField(blank=True, max_length=10, verbose_name='Salt')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ('-date_joined',),
            },
        ),
    ]
